import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { copy } from './site-copy.mjs';

const base='https://sofamate.aveniqa.com', zip='https://github.com/UncleK/SofaMate/releases/latest/download/SofaMate-Windows-x64.zip';
const revision=createHash('sha256').update(JSON.stringify(copy)).update(await readFile('site/app.js')).update(await readFile('site/style.css')).digest('hex').slice(0,12);
const pages=['index','market','about','download','login','privacy'];
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const video='/previews/night-scene.mp4?v=E12';
const siteUrl=(lang,page)=>`${lang==='zh'?'':'/'+lang}/${page==='index'?'':page}`;
for(const [lang,c] of Object.entries(copy)) {
  const url=page=>siteUrl(lang,page), e=escape;
  const link=(page,label,cls='')=>`<a class="${cls}" href="${url(page)}">${e(label)}</a>`;
  const cover=(poster='night-close.png')=>`<button class="companion-cover" data-preview="${video}" aria-label="${e(c.play)}"><img src="/assets/companions/${poster}" width="1280" height="720" alt="${e(c.night)}" fetchpriority="high"><span>▶ ${e(c.play)}</span></button>`;
  const start=()=>`<a class="button primary" href="${url('download')}?theme=living-room-night">${e(c.start)} <span>↗</span></a>`;
  const official=`<article class="companion-card" id="official-scene">${cover()}<div class="companion-info"><div><span class="scene-label">${e(c.official)}</span><h2>${e(c.night)}</h2><p>${e(c.nightDescription)}</p></div>${start()}</div></article>`;
  for(const page of pages) {
    const title=page==='index'?c.tagline:c[{market:'discover',about:'about',download:'download',login:'login',privacy:'privacy'}[page]];
    const canonical=base+url(page);
    const nav=`<header class="site-header wrap"><a class="wordmark" href="${url('index')}"><img src="/assets/icon.png" width="30" height="30" alt="">SofaMate${lang==='zh'?'<span class="brand-cn">沙发伴侣</span>':''}</a><nav aria-label="${e(c.home)}">${[['index','home'],['market','discover'],['about','about'],['download','download']].map(([p,k])=>`<a href="${url(p)}"${p===page?' aria-current="page"':''}>${e(c[k])}</a>`).join('')}</nav><div class="header-tools"><select id="site-language" aria-label="${e(c.language)}">${[['zh','简体中文'],['en','English'],['ja','日本語']].map(([v,t])=>`<option value="${v}"${v===lang?' selected':''}>${t}</option>`).join('')}</select><a id="site-account" class="nav-account" href="${url('login')}">${e(c.login)}</a></div></header>`;
    let body='';
    if(page==='index') body=`<main class="home-main"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="live-dot"></span> SOFAMATE / DESKTOP COMPANY</p><h1>${e(c.heroA)}<br><em>${e(c.heroB)}</em></h1><p class="hero-description">${e(c.intro)}</p><div class="hero-actions">${link('download',c.start+' ↗','button primary')}${link('market',c.explore+' ↗','text-link')}</div><p class="hero-footnote">${e(c.basics)}</p></div><div class="hero-visual"><div class="orbit orbit-one"></div><div class="hero-caption"><span>01 / EVENING TOGETHER</span><span>${e(c.official)}</span></div><figure class="app-frame companion-spotlight">${cover()}<figcaption><div><strong>${e(c.night)}</strong><p>${e(c.nightDescription)}</p></div>${start()}</figcaption></figure><p class="visual-bottom">${e(c.sample)}</p></div></section><div class="home-bottom wrap"><p>${e(c.homeNote)}</p>${link('about',c.learn+' ↗','text-link')}</div></main>`;
    if(page==='market') body=`<main class="subpage wrap"><div class="subpage-heading"><div><p class="eyebrow">FIND YOUR KIND OF COMPANY.</p><h1>${e(c.discoverTitle)}</h1><p class="subpage-lead">${e(c.discoverIntro)}</p></div><form class="search-form" id="market-search"><input type="search" id="market-query" placeholder="${e(c.searchPlaceholder)}" aria-label="${e(c.searchPlaceholder)}" maxlength="100"><button class="button">${e(c.search)} ↗</button></form></div><label class="market-filter">${e(c.featured)} <select id="market-filter" aria-label="${e(c.featured)}"><option value="0">${e(c.allWorks)}</option><option value="1">${e(c.featured)}</option></select></label><p id="market-status" role="status"></p><div class="market-grid" id="market-grid"></div><div class="market-empty" id="market-empty" hidden><h2>${e(c.empty)}</h2><p>${e(c.emptyHelp)}</p></div><button class="button" id="market-reset" hidden>${e(c.reset)}</button><button class="button" id="market-more" hidden>${e(c.more)}</button></main>`;
    if(page==='about') body=`<main class="subpage wrap about-page"><div class="page-heading"><p class="eyebrow">YOUR KIND OF COMPANY.</p><h1>${e(c.aboutTitle)}</h1><p class="subpage-lead">${e(c.aboutIntro)}</p></div><figure class="character-pair"><div><img src="/assets/companions/night-close.png" alt="${e(c.night)}" width="1280" height="720"><img src="/assets/companions/day-companion.png" alt="SofaMate — ${lang==='zh'?'新角色形象':lang==='ja'?'新キャラクターのイメージ':'New character artwork'}" width="1448" height="1086"></div><figcaption>${e(c.artNote)}</figcaption></figure><div class="about-features">${c.features.map(([h,p],i)=>`<article><span class="eyebrow">0${i+1}</span><h2>${e(h)}</h2><p>${e(p)}</p></article>`).join('')}</div><div class="about-links">${link('market',c.discover+' ↗','text-link')}${link('download',c.download+' ↗','button primary')}</div><section class="faq-section"><h2>${e(c.faqTitle)}</h2><div class="faq-list">${c.faqs.map(([q,a])=>`<details><summary>${e(q)}</summary><p>${e(a)}</p></details>`).join('')}</div></section></main>`;
    if(page==='download') body=`<main class="subpage wrap download-page"><div class="page-heading"><p class="eyebrow">A LITTLE COMPANY, EVERY DAY.</p><h1>${e(c.downloadTitle)}</h1><p class="subpage-lead">${e(c.downloadIntro)}</p></div><section class="download-panel"><div class="download-brand"><img src="/assets/icon.png" width="64" height="64" alt=""><div><h2>SofaMate <span>for Windows</span></h2><p>${e(c.beta)}</p></div></div><a class="button primary download-main" href="${zip}">${e(c.downloadWindows)} <span>↓</span></a><p class="download-size">${e(c.downloadSize)}</p><p class="download-spec">${e(c.requirements)}</p><a class="text-link" href="https://github.com/UncleK/SofaMate/releases">${e(c.releaseNotes)} ↗</a><div class="selected-scene" id="selected-scene" hidden><p id="selected-description">${e(c.selected)}</p><a class="text-link" id="selected-download" download="SofaMate-E12.mp4">${e(c.videoDownload)} ↓</a></div></section><div class="download-steps">${c.downloadSteps.map(([h,p],i)=>`<article><span>0${i+1}</span><h2>${e(h)}</h2><p>${e(p)}</p></article>`).join('')}</div><section class="download-quality"><h2>${e(c.qualityTitle)}</h2><p>${e(c.qualityNote)}</p><p>${e(c.applyNote)}</p></section><p class="download-limits">${e(c.videoLimits)}</p></main>`;
    if(page==='login') body=`<main class="subpage wrap"><div class="auth-layout"><div class="auth-intro"><p class="eyebrow">YOUR KIND OF COMPANY.</p><h1>${e(c.loginTitle)}</h1><p>${e(c.loginIntro)}</p><div class="auth-decoration"></div></div><section class="auth-card" aria-labelledby="auth-title"><p class="eyebrow">AVENIQA ACCOUNT</p><h2 id="auth-title">${e(c.welcome)}</h2><div id="unified-sign-in"><p>${e(c.accountIntro)}</p><a class="button primary unified-login" id="unified-login" href="/v1/auth/aveniqa/start">${e(c.continue)} <span>→</span></a><div class="identity-methods"><img src="/assets/google-mark.png" width="20" height="20" alt="Google"><img src="/assets/github-mark.svg" width="20" height="20" alt="GitHub"><span>${e(c.methods)}</span></div><p>${e(c.registerNote)}</p></div><div id="signed-in" hidden><p class="auth-user" id="user-name"></p><p id="user-email"></p><div id="pairing" hidden><p>${e(c.pairPrompt)}</p><div class="auth-code" id="pair-code"></div><button class="button primary" id="approve-desktop">${e(c.pair)}</button><p>${e(c.pairNote)}</p></div><div id="account-actions">${link('market',c.discover+' ↗','button primary')}</div><button class="auth-secondary" id="sign-out">${e(c.logout)}</button></div><p class="auth-status" id="auth-status" role="status" aria-live="polite"></p><p class="auth-privacy">${link('privacy',c.privacy)}</p></section></div></main>`;
    if(page==='privacy') body=`<main class="subpage wrap prose"><h1>${e(c.privacyTitle)}</h1><p>${e(c.updated)}</p>${c.privacySections.map(([h,p])=>`<h2>${e(h)}</h2><p>${e(p)}</p>`).join('')}<a href="https://github.com/UncleK/SofaMate/issues">GitHub Issues ↗</a></main>`;
    const footer=`<footer class="site-footer wrap"><a class="wordmark" href="${url('index')}">SofaMate</a><span>A little company, every day.</span><div>${link('privacy',c.privacy)}<a href="https://github.com/UncleK/SofaMate">GitHub ↗</a><a href="https://github.com/UncleK/SofaMate/issues">${e(c.feedback)}</a></div></footer>`;
    const structured={ '@context':'https://schema.org', '@graph': [{ '@type':'WebSite',name:'SofaMate',url:base+url('index'),inLanguage:c.locale}, ...(page==='index'?[{'@type':'SoftwareApplication',name:'SofaMate',description:c.seo,applicationCategory:'LifestyleApplication',operatingSystem:'Windows 10 / 11 x64',inLanguage:['zh-CN','en','ja'],softwareVersion:'0.1.0',downloadUrl:zip,offers:{'@type':'Offer',price:0,priceCurrency:'USD'}}]:[]),...(page==='about'?[{'@type':'FAQPage',mainEntity:c.faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]:[])]};
    const html=`<!doctype html><html lang="${c.locale}" data-language="${lang}" data-page="${page}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · SofaMate</title><meta name="description" content="${e(c.seo)}"><meta name="theme-color" content="#22211f"><link rel="icon" href="/assets/icon.png"><link rel="stylesheet" href="/style.css?v=${revision}"><script defer src="/i18n.js?v=${revision}"></script><script defer src="/app.js?v=${revision}"></script><link rel="canonical" href="${canonical}">${Object.keys(copy).map(l=>`<link rel="alternate" hreflang="${copy[l].locale}" href="${base+siteUrl(l,page)}">`).join('')}<link rel="alternate" hreflang="x-default" href="${base+siteUrl('zh',page)}">${page==='login'?'<meta name="robots" content="noindex">':''}<meta property="og:type" content="website"><meta property="og:site_name" content="SofaMate"><meta property="og:url" content="${canonical}"><meta property="og:locale" content="${{zh:'zh_CN',en:'en_US',ja:'ja_JP'}[lang]}"><meta property="og:title" content="${e(title)} · SofaMate"><meta property="og:description" content="${e(c.seo)}"><meta property="og:image" content="${base}/assets/social-card.png?v=portraits"><meta property="og:image:width" content="1600"><meta property="og:image:height" content="620"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${e(title)} · SofaMate"><meta name="twitter:description" content="${e(c.seo)}"><meta name="twitter:image" content="${base}/assets/social-card.png?v=portraits"><script type="application/ld+json">${JSON.stringify(structured).replaceAll('<','\\u003c')}</script></head><body>${nav}${body}${footer}</body></html>`;
    const dir=lang==='zh'?'site':`site/${lang}`;await mkdir(dir,{recursive:true});await writeFile(`${dir}/${page}.html`,html+'\n');
  }
}
const runtimeKeys=['login','account','welcome','officialPublisher','completeTheme','selectedTheme','locale','night','search','community','loading','empty','emptyHelp','count','featured','official','fullTheme','galleryError','start','play','connected','welcomeBack','configuring','unavailable','frequent'];
const runtime=Object.fromEntries(Object.entries(copy).map(([l,c])=>[l,Object.fromEntries(runtimeKeys.map(k=>[k,c[k]]))]));
await writeFile('site/i18n.js',`window.sofaCopy=${JSON.stringify(runtime)}[document.documentElement.dataset.language] || ${JSON.stringify(runtime.zh)};\n`);
await writeFile('site/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+Object.keys(copy).flatMap(l=>pages.filter(p=>p!=='login').map(p=>`<url><loc>${base+siteUrl(l,p)}</loc></url>`)).join('')+'</urlset>\n');
console.log('Built 18 localized pages and a 15-URL sitemap.');
