// Website copy is rendered into static pages for each language.
export const copy = {
  zh: {
    locale:'zh-CN', home:'首页', discover:'发现', about:'关于', download:'下载', login:'登录 / 注册', privacy:'隐私说明', feedback:'反馈', language:'语言',
    tagline:'打开桌面，就有陪伴。', heroA:'打开桌面，', heroB:'就有陪伴。', intro:'把喜欢的身影留在桌面。工作、学习，或一个人待着时，多一份陪伴。', start:'立即陪伴', explore:'发现喜欢的角色',
    night:'夜间客厅', nightDescription:'靠近一点，陪你度过一起待着的夜晚。', play:'播放预览', official:'官方 · 视频片段', sample:'走近、跪下，轻轻擦拭屏幕。此示例为单个视频片段。',
    basics:'Windows 10 / 11 · 免安装 · 默认静音', homeNote:'轻巧的客户端，让喜欢的角色陪在身边。', learn:'了解 SofaMate',
    discoverTitle:'今天，想和谁待一会儿？', discoverIntro:'看看喜欢的身影，把这份陪伴带回桌面。浏览与下载无需登录。', search:'搜索', searchPlaceholder:'搜索作品、作者', all:'全部作品', community:'社区', more:'加载更多', loading:'正在寻找喜欢的画面…', empty:'还没有找到匹配的作品。', emptyHelp:'试试其他名字，或清空搜索看看全部作品。', reset:'清空搜索', count:'段画面，等你带回桌面。', galleryError:'社区作品暂时无法加载，你仍可以预览官方片段。',
    aboutTitle:'喜欢的身影，陪在身边。', aboutIntro:'喜欢她的温柔，也可以喜欢他的笑容。选择让你心动的角色，让独处的日常多一份陪伴。', artNote:'左：夜间客厅实际角色。右：新角色形象设计，视频尚未发布。',
    features:[['收下你的喜欢。','导入 MP4，自动生成九宫格。搜索、预览，再设为桌面壁纸。'],['陪伴，由你安排。','预览与桌面播放各自控制。暂停、继续或停止，随时由你决定。'],['把喜欢分享出去。','用 Aveniqa 账号登录后发布作品。其他人可以浏览、下载，在自己的桌面使用。']],
    faqTitle:'开始之前，你可能想知道。', faqs:[['SofaMate 能聊天吗？','当前通过视频呈现桌面陪伴，不提供 AI 聊天、语音对话或实时互动。'],['必须注册吗？','导入、播放、浏览与下载无需注册。发布和管理作品需要登录；邮箱验证码、Google 和 GitHub 使用统一的 Aveniqa 账号。'],['会自动上传我的视频吗？','不会。视频与九宫格保存在本机，只有你主动分享时才上传。请仅分享你有权公开分发的内容。'],['客户端会占很多资源吗？','下载包约 1.89 MiB，使用系统 WebView2，不捆绑浏览器。停止会销毁桌面播放器，托盘仍保留；视频资源占用取决于分辨率和编码。']],
    downloadTitle:'把陪伴，带回桌面。', downloadIntro:'一个小小的客户端，装下你的喜欢。', downloadWindows:'下载 Windows 版', downloadSize:'ZIP · 1.89 MiB · 免安装', requirements:'Windows 10 / 11 x64 · 需要系统 WebView2 Runtime', beta:'v0.1.0 公开测试版 · 未签名', releaseNotes:'版本说明', downloadSteps:[['解压并打开','下载 ZIP，解压后打开 SofaMate.exe。'],['选择喜欢的视频','导入你自己的 MP4，或从「发现」下载作品。'],['设为壁纸','先预览，再点击「设为壁纸」。双击托盘返回面板。']], videoDownload:'下载示例视频', selected:'已为你带上选中的视频。', videoLimits:'支持 H.264 / AAC MP4，单视频最大 1 GiB，当前支持单主屏。公开包不附带视频。',
    loginTitle:'遇见喜欢的陪伴。', loginIntro:'发现喜欢的桌面角色，也分享你创作的陪伴视频。', welcome:'欢迎来到 SofaMate', accountIntro:'一个账号，即可登录 Aveniqa 和 SofaMate。', continue:'使用 Aveniqa 账号继续', methods:'Google · GitHub · 邮箱验证码', registerNote:'首次登录可在账号中心注册。浏览、下载与本机播放无需登录。', pairPrompt:'请核对客户端显示的配对码：', pair:'连接 SofaMate 客户端', pairNote:'仅连接你自己刚刚打开的客户端。', logout:'退出 SofaMate', connected:'已连接。可以返回 SofaMate 客户端了。', welcomeBack:'很高兴，再见到你。', configuring:'统一登录正在配置，请稍后重试。', unavailable:'服务暂时不可用，请稍后重试。', frequent:'操作太频繁，请稍后再试。',
    privacyTitle:'隐私与分享说明', updated:'更新于 2026 年 9 月 20 日。本说明描述公开测试版的数据处理方式。', privacySections:[['本机视频','导入的视频复制到本机壁纸库。九宫格在你的电脑上生成。导入、预览和设为壁纸不会自动上传文件；主动分享时才上传视频、预览图、标题和简介。'],['账号与登录','SofaMate 与 Aveniqa 共用账号，支持邮箱验证码、GitHub 和 Google。注册和验证在 Aveniqa 账号中心完成。SofaMate 接收账号标识、已验证邮箱和公开昵称，用于登录及作品归属。两款产品分别管理作品、额度和权限；SofaMate 不获取 Aveniqa 业务数据库、GitHub 仓库或 Google 云盘权限。'],['登录会话','网站仅使用安全、HttpOnly 的必要登录 Cookie，不使用广告或跨站分析 Cookie。客户端凭据由 Windows 用户级加密保存，不进入渲染页面。退出 SofaMate 撤销当前 SofaMate 会话，不等同于退出所有产品。'],['公开分享','发布后的昵称、标题、简介、视频和预览图可公开浏览与下载，邮箱不会公开。请仅分享你有权分发的内容。你可撤回作品，关闭服务器公开访问；其他人已下载的副本仍由对方持有。'],['容量与管理','单视频最大 1 GiB，每账号总容量 2 GiB（含预览预留空间），最多 50 条。过期草稿会清理。管理员可下架作品、停用滥用账号。必要运行日志不记录验证码、凭据或完整 OAuth 回调参数。'],['联系我们','功能问题、内容投诉或账号数据删除请求，请通过 GitHub Issues 联系维护者。公开留言不要包含验证码、凭据或私人信息；账号归属请求需验证身份。']],
    seo:'轻巧的 Windows 桌面视频陪伴软件。发现喜欢的角色，预览真实视频，下载 SofaMate，把陪伴带回桌面。'
  },
  en: {
    locale:'en', home:'Home', discover:'Discover', about:'About', download:'Download', login:'Sign in', privacy:'Privacy', feedback:'Feedback', language:'Language',
    tagline:'A familiar face. A little company.', heroA:'A familiar face.', heroB:'A little company.', intro:'Keep your favorite characters on your desktop. A little company through work, study and time on your own.', start:'Bring them home', explore:'Find your companion',
    night:'Evening living room', nightDescription:'A little closer. A familiar face to share the evening with.', play:'Play preview', official:'Official · Video excerpt', sample:'A close-up moment: approaching, kneeling and gently wiping the screen. This is a single video excerpt.',
    basics:'Windows 10 / 11 · Portable · Starts muted', homeNote:'A lightweight app. Your kind of company.', learn:'Meet SofaMate',
    discoverTitle:'Who will keep you company today?', discoverIntro:'Find a familiar face and bring them to your desktop. No account needed to browse or download.', search:'Search', searchPlaceholder:'Search works or creators', all:'All works', community:'Community', more:'Load more', loading:'Finding your next favorite…', empty:'No matching works yet.', emptyHelp:'Try another name, or clear your search to see everything.', reset:'Clear search', count:'videos to bring to your desktop.', galleryError:'Community works could not be loaded. You can still watch the official excerpt.',
    aboutTitle:'Your favorite faces, beside you.', aboutIntro:'Her warmth, his smile, or a character you simply love. Choose your kind of company for the moments you spend on your own.', artNote:'Left: the character from Evening living room. Right: new character artwork; video not yet released.',
    features:[['Keep your favorites.','Import an MP4 and get a nine-frame preview. Search, preview and set it as your wallpaper.'],['Company on your terms.','Panel preview and desktop playback have separate controls. Pause, resume or stop whenever you like.'],['Share a little company.','Publish with your Aveniqa account. Others can browse, download and enjoy your videos on their own desktop.']],
    faqTitle:'A few things before you begin.', faqs:[['Can SofaMate chat with me?','The current version offers companionship through video. AI chat, voice conversations and real-time interaction are not included.'],['Do I need an account?','Importing, playback, browsing and downloads do not require an account. Publishing and managing works does. Email codes, Google and GitHub use one shared Aveniqa account.'],['Are my videos uploaded automatically?','No. Videos and nine-frame previews stay on your computer unless you choose to share. Only share content you have the right to distribute.'],['Is it resource-heavy?','The download is about 1.89 MiB and uses system WebView2 without bundling a browser. Stop destroys the desktop player while keeping the tray. Playback resource use depends on video resolution and encoding.']],
    downloadTitle:'Bring your company home.', downloadIntro:'A small app, with room for your favorites.', downloadWindows:'Download for Windows', downloadSize:'ZIP · 1.89 MiB · Portable', requirements:'Windows 10 / 11 x64 · System WebView2 Runtime required', beta:'v0.1.0 public beta · Unsigned', releaseNotes:'Release notes', downloadSteps:[['Extract and open','Download the ZIP, extract it and open SofaMate.exe.'],['Choose a video','Import your own MP4 or download a work from Discover.'],['Set as wallpaper','Preview, then choose “Set as wallpaper”. Double-click the tray icon to return.']], videoDownload:'Download sample video', selected:'Your selected video is ready to download too.', videoLimits:'H.264 / AAC MP4, up to 1 GiB per video. Primary monitor supported. Videos are not bundled.',
    loginTitle:'Find your kind of company.', loginIntro:'Discover desktop characters you love, and share the companion videos you create.', welcome:'Welcome to SofaMate', accountIntro:'One account for Aveniqa and SofaMate.', continue:'Continue with Aveniqa', methods:'Google · GitHub · Email code', registerNote:'New here? Register at the account center. Browsing, downloads and local playback need no account.', pairPrompt:'Check the pairing code shown in your desktop app:', pair:'Connect SofaMate desktop', pairNote:'Only connect the app you just opened yourself.', logout:'Sign out of SofaMate', connected:'Connected. You can return to the SofaMate app.', welcomeBack:'Good to see you again.', configuring:'Unified sign-in is being configured. Please try again later.', unavailable:'Service unavailable. Please try again later.', frequent:'Too many requests. Please try again shortly.',
    privacyTitle:'Privacy and sharing', updated:'Updated September 20, 2026. This notice describes data handling in the public beta.', privacySections:[['Local videos','Imported videos are copied to your local library. Nine-frame previews are generated on your computer. Importing, previewing and setting a wallpaper do not upload files. Choosing Share uploads the video, preview, title and description.'],['Accounts and sign-in','SofaMate and Aveniqa share an account center with email codes, GitHub and Google. Registration and authentication happen at Aveniqa. SofaMate receives your account identifier, verified email and public name for sign-in and work ownership. Each product manages its own works, credits and permissions. SofaMate receives no access to the Aveniqa business database, GitHub repositories or Google Drive.'],['Sessions','The website uses secure, HttpOnly essential sign-in cookies, without advertising or cross-site analytics cookies. Desktop credentials are encrypted for your Windows user and kept out of the renderer. Signing out of SofaMate revokes the current SofaMate session; it does not sign you out of every product.'],['Public sharing','Published names, titles, descriptions, videos and previews are public and downloadable. Email addresses are not public. Only share content you may distribute. Withdrawing a work closes public server access; copies already downloaded remain with their recipients.'],['Storage and moderation','Each video may be up to 1 GiB. Each account has 2 GiB including preview allowance, and up to 50 works. Expired drafts are removed. Administrators can remove works and disable abusive accounts. Essential operational logs exclude verification codes, credentials and full OAuth callback parameters.'],['Contact','Use GitHub Issues for product questions, content complaints or account deletion requests. Do not include codes, credentials or private information in public comments. Account ownership requests require identity verification.']],
    seo:'A lightweight Windows video companion app. Discover favorite characters, watch real previews and bring a little company to your desktop with SofaMate.'
  },
  ja: {
    locale:'ja', home:'ホーム', discover:'見つける', about:'SofaMateについて', download:'ダウンロード', login:'ログイン', privacy:'プライバシー', feedback:'フィードバック', language:'言語',
    tagline:'デスクトップに、そばにいる温もりを。', heroA:'デスクトップに、', heroB:'そばにいる温もりを。', intro:'お気に入りの姿を、いつものデスクトップに。仕事や勉強、ひとりの時間に、そっと寄り添う存在を。', start:'そばに迎える', explore:'お気に入りを見つける',
    night:'夜のリビング', nightDescription:'もう少し近くに。一緒に過ごす、いつもの夜。', play:'プレビューを再生', official:'公式 · 動画サンプル', sample:'近づいて、ひざをつき、画面をそっと拭くひととき。単独の動画サンプルです。',
    basics:'Windows 10 / 11 · インストール不要 · 初期状態はミュート', homeNote:'軽やかなアプリで、お気に入りをそばに。', learn:'SofaMateを知る',
    discoverTitle:'今日は、誰と過ごしますか？', discoverIntro:'お気に入りの姿を見つけて、デスクトップへ。閲覧とダウンロードに登録は不要です。', search:'検索', searchPlaceholder:'作品名・作者を検索', all:'すべての作品', community:'コミュニティ', more:'もっと見る', loading:'お気に入りを探しています…', empty:'一致する作品がありません。', emptyHelp:'別の名前を試すか、検索をクリアしてすべての作品をご覧ください。', reset:'検索をクリア', count:'本の動画をデスクトップへ。', galleryError:'コミュニティ作品を読み込めませんでした。公式サンプルはご覧いただけます。',
    aboutTitle:'お気に入りの姿を、すぐそばに。', aboutIntro:'彼女の優しさも、彼の笑顔も。心ひかれるキャラクターを選んで、ひとりの時間に温もりを。', artNote:'左：夜のリビングの実際のキャラクター。右：新キャラクターのイメージ。動画は未公開です。',
    features:[['お気に入りを集める。','MP4を読み込むと9コマのプレビューを自動作成。検索して、確認して、壁紙に設定できます。'],['自分のペースで。','ウィンドウ内のプレビューとデスクトップ再生は別々に操作。一時停止、再開、停止もいつでも。'],['好きな気持ちを届ける。','Aveniqaアカウントで作品を公開。ほかの人も閲覧・ダウンロードして、自分のデスクトップで楽しめます。']],
    faqTitle:'はじめる前に。', faqs:[['SofaMateと会話できますか？','現在は動画によるデスクトップでの寄り添い体験です。AIチャット、音声会話、リアルタイムの対話には対応していません。'],['登録は必要ですか？','読み込み、再生、閲覧、ダウンロードは登録不要です。作品の公開・管理にはログインが必要です。メール認証コード、Google、GitHubで共通のAveniqaアカウントを利用します。'],['動画は自動でアップロードされますか？','いいえ。動画と9コマのプレビューはPC内に保存され、自分で共有を選んだときだけアップロードされます。配布する権利のある作品のみ共有してください。'],['アプリは重いですか？','ダウンロードは約1.89 MiB。システムのWebView2を使用し、ブラウザーを同梱しません。停止するとデスクトッププレイヤーを終了し、トレイは残ります。再生負荷は動画の解像度や形式によって異なります。']],
    downloadTitle:'お気に入りを、デスクトップへ。', downloadIntro:'小さなアプリに、あなたの「好き」を。', downloadWindows:'Windows版をダウンロード', downloadSize:'ZIP · 1.89 MiB · インストール不要', requirements:'Windows 10 / 11 x64 · システムのWebView2 Runtimeが必要', beta:'v0.1.0 公開ベータ版 · 未署名', releaseNotes:'リリースノート', downloadSteps:[['解凍して開く','ZIPをダウンロードして解凍し、SofaMate.exeを開きます。'],['動画を選ぶ','自分のMP4を読み込むか、「見つける」から作品をダウンロードします。'],['壁紙に設定','プレビュー後に「壁紙に設定」を選びます。トレイをダブルクリックするとパネルに戻ります。']], videoDownload:'サンプル動画をダウンロード', selected:'選んだ動画も、こちらからダウンロードできます。', videoLimits:'H.264 / AACのMP4、1本最大1 GiB。現在はメインモニターに対応。動画は同梱していません。',
    loginTitle:'お気に入りの存在に出会う。', loginIntro:'好きなデスクトップキャラクターを見つけて、自分の作品も共有しましょう。', welcome:'SofaMateへようこそ', accountIntro:'ひとつのアカウントで、AveniqaとSofaMateにログイン。', continue:'Aveniqaで続ける', methods:'Google · GitHub · メール認証コード', registerNote:'初めての方はアカウントセンターで登録できます。閲覧、ダウンロード、ローカル再生は登録不要です。', pairPrompt:'PCアプリに表示されたペアリングコードを確認してください：', pair:'SofaMateアプリを接続', pairNote:'自分で開いたアプリだけを接続してください。', logout:'SofaMateからログアウト', connected:'接続しました。SofaMateアプリに戻れます。', welcomeBack:'また会えてうれしいです。', configuring:'共通ログインを設定中です。しばらくしてからお試しください。', unavailable:'現在サービスを利用できません。しばらくしてからお試しください。', frequent:'操作が多すぎます。少し待ってからお試しください。',
    privacyTitle:'プライバシーと共有について', updated:'更新日：2026年9月20日。公開ベータ版でのデータの取り扱いについて説明します。', privacySections:[['ローカル動画','読み込んだ動画はPC内の壁紙ライブラリへコピーされます。9コマのプレビューもPC内で生成します。読み込み、プレビュー、壁紙設定だけではアップロードされません。共有を選ぶと、動画、プレビュー画像、タイトル、説明がアップロードされます。'],['アカウントとログイン','SofaMateとAveniqaはメール認証コード、GitHub、Googleに対応する共通アカウントを使用します。登録と認証はAveniqaで行います。SofaMateはログインと作品の所有者確認のため、アカウントID、確認済みメールアドレス、公開名を受け取ります。作品、クレジット、権限は製品ごとに管理されます。Aveniqaの業務データベース、GitHubリポジトリ、Googleドライブへの権限は取得しません。'],['ログインセッション','サイトは安全なHttpOnlyの必須ログインCookieのみを使用し、広告やサイト横断分析のCookieは使いません。アプリの認証情報はWindowsユーザー単位で暗号化し、描画画面には渡しません。SofaMateからのログアウトは現在のSofaMateセッションを無効にし、全製品からのログアウトにはなりません。'],['公開共有','公開後の名前、タイトル、説明、動画、プレビューは誰でも閲覧・ダウンロードできます。メールアドレスは公開しません。配布する権利のある作品のみ共有してください。作品を取り下げるとサーバーでの公開は終了しますが、すでにダウンロードされたコピーは相手の手元に残ります。'],['容量と管理','動画は1本最大1 GiB、アカウントごとにプレビュー用領域を含む合計2 GiB、最大50作品です。期限切れの下書きは削除されます。管理者は作品の非公開化や不正利用アカウントの停止を行えます。運用ログには認証コード、認証情報、OAuthコールバックの完全なパラメーターを記録しません。'],['お問い合わせ','機能の質問、作品の通報、アカウント削除の依頼はGitHub Issuesからご連絡ください。公開コメントに認証コードや認証情報、個人情報を書かないでください。アカウントの所有者確認が必要な依頼には本人確認を行います。']],
    seo:'軽量なWindows向けデスクトップ動画コンパニオン。お気に入りのキャラクターを見つけ、動画をプレビューして、SofaMateでそばに迎えましょう。'
  }
};
